import { INITIAL_HOME_DATA, INITIAL_MINISTRIES_DATA, INITIAL_FOOTER_DATA, INITIAL_HEADER_DATA, INITIAL_PAGES_DATA } from './initialData';

export {
  INITIAL_HOME_DATA,
  INITIAL_MINISTRIES_DATA,
  INITIAL_FOOTER_DATA,
  INITIAL_HEADER_DATA,
  INITIAL_PAGES_DATA
};
