-- ==========================================
-- SCRIPT DE CONFIGURAÇÃO ADMAC - SUPABASE
-- Execute este script no SQL Editor do Supabase
-- ==========================================

-- 1. Tabela de Configurações (site_settings)
CREATE TABLE IF NOT EXISTS public.site_settings (
    key TEXT PRIMARY KEY,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativar RLS (Row Level Security)
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Políticas site_settings
CREATE POLICY "Permitir leitura pública" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Permitir upsert total" ON public.site_settings FOR ALL USING (true);

-- 2. Tabela de Usuários (site_users)
CREATE TABLE IF NOT EXISTS public.site_users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'Viewer',
    status TEXT DEFAULT 'active',
    location TEXT,
    photo TEXT,
    since TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativar RLS
ALTER TABLE public.site_users ENABLE ROW LEVEL SECURITY;

-- Políticas site_users
CREATE POLICY "Leitura de usuários" ON public.site_users FOR SELECT USING (true);
CREATE POLICY "Gestão de usuários" ON public.site_users FOR ALL USING (true);

-- 3. Tabela de Mensagens (site_messages)
CREATE TABLE IF NOT EXISTS public.site_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    category TEXT,
    message TEXT,
    type TEXT DEFAULT 'contact', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativar RLS
ALTER TABLE public.site_messages ENABLE ROW LEVEL SECURITY;

-- Políticas site_messages
CREATE POLICY "Inserção pública de mensagens" ON public.site_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Gestão de mensagens" ON public.site_messages FOR ALL USING (true);

-- 4. Tabela de Logs (site_logs)
CREATE TABLE IF NOT EXISTS public.site_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT,
    action TEXT,
    detail TEXT,
    type TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativar RLS
ALTER TABLE public.site_logs ENABLE ROW LEVEL SECURITY;

-- Políticas site_logs
CREATE POLICY "Leitura de logs" ON public.site_logs FOR SELECT USING (true);
CREATE POLICY "Inserção de logs" ON public.site_logs FOR INSERT WITH CHECK (true);

-- 5. Trigger para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.site_settings
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- 6. Configuração de Storage (Bucket para Fotos)
-- Nota: O Supabase não permite criar buckets via SQL puro de forma simples sem extensões de admin.
-- Por favor, vá em Storage -> New Bucket e crie um chamado "site-images" e torne-o PUBLIC.
